### PR TITLE
Add updatePhoneNumber sdk method

### PR DESCRIPTION
**Pull request by mushfichowdhury-magic**
### 📦 Pull Request

Added in `.updatePhoneNumber` method for sdk as per Clubhouse deliverable

### ✅ Fixed Issues

- [List any fixed issues here like: Fixes #XXXX]

### 🚨 Test instructions

[Describe any additional context required to test the PR/feature/bug fix.]

### ⚠️ Don't forget to add a [semver](https://semver.org/) label!

- `patch`: Bug Fix?
- `minor`: New Feature?
- `major`: Breaking Change?
- `skip-release`: It's unnecessary to publish this change.

### CODE REVIEW

**Comment by Ariflo** [comment]
> @Ariflo I added a new sdk method for a Clubhouse deliverable, will there be any updates needed on the mobile end?

Thanks for the heads up @mushfichowdhury-magic, yes this will need equivalent changes on our native iOS and Android SDK.

**Review by Ariflo — CHANGES_REQUESTED** [review]
It looks like this PR needs some yarn.lock updates.

**Review by Ariflo — APPROVED** [review]
LGTM

**Comment by magiclabsFE** [comment]
:rocket: PR was released in [`@magic-ext/algorand@8.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/algorand%408.3.0), [`@magic-ext/avalanche@8.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/avalanche%408.3.0), [`@magic-ext/bitcoin@8.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/bitcoin%408.3.0), [`@magic-ext/conflux@6.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/conflux%406.3.0), [`@magic-ext/connect@6.4.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/connect%406.4.0), [`@magic-ext/cosmos@8.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/cosmos%408.3.0), [`@magic-ext/ed25519@4.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/ed25519%404.3.0), [`@magic-ext/flow@8.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/flow%408.3.0), [`@magic-ext/harmony@8.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/harmony%408.3.0), [`@magic-ext/icon@8.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/icon%408.3.0), [`@magic-ext/near@8.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/near%408.3.0), [`@magic-ext/oauth@7.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/oauth%407.3.0), [`@magic-ext/polkadot@8.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/polkadot%408.3.0), [`@magic-ext/react-native-bare-oauth@8.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/react-native-bare-oauth%408.3.0), [`@magic-ext/react-native-expo-oauth@8.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/react-native-expo-oauth%408.3.0), [`@magic-ext/solana@9.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/solana%409.3.0), [`@magic-ext/taquito@5.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/taquito%405.3.0), [`@magic-ext/terra@5.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/terra%405.3.0), [`@magic-ext/tezos@8.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/tezos%408.3.0), [`@magic-ext/webauthn@7.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/webauthn%407.3.0), [`@magic-ext/zilliqa@8.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/zilliqa%408.3.0), [`@magic-sdk/commons@9.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/commons%409.3.0), [`@magic-sdk/pnp@7.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/pnp%407.3.0), [`@magic-sdk/provider@13.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/provider%4013.3.0), [`@magic-sdk/react-native-bare@14.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/react-native-bare%4014.3.0), [`@magic-sdk/react-native-expo@14.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/react-native-expo%4014.3.0), [`@magic-sdk/types@11.3.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/types%4011.3.0), [`magic-sdk@13.3.0`](https://github.com/magiclabs/magic-js/releases/tag/magic-sdk%4013.3.0) :rocket:

**Pull request merged**
