### PR TITLE
Patch Update README [#99]

### PR DESCRIPTION
**Pull request by EthanThatOneKid**
### 📦 Pull Request

CircleCI badge correction in README

### 🗜 Versioning

- [x] Patch: Bug Fix?
- [ ] Minor: New Feature?
- [ ] Major: Breaking Change?

### ✅ Fixed Issues

- Fixes [#99](https://github.com/magiclabs/magic-js/issues/99#issue-627513141)

### 🚨 Test instructions

No testing necessary.

### ⚠️ Update `CHANGELOG.md`

- [x] I have updated the `Upcoming Changes` section of `CHANGELOG.md` with context related to this Pull Request.

### CODE REVIEW

**Comment by smithki** [comment]
Thank you for your contribution! 🙏 

Just one thing, do you mind changing your PR label to a “patch” fix so it’s not misinterpreted the next time we cut a release?

**Comment by EthanThatOneKid** [comment]
> Thank you for your contribution! 🙏
> 
> Just one thing, do you mind changing your PR label to a “patch” fix so it’s not misinterpreted the next time we cut a release?

No problem; I just fixed that in the 🗜 Versioning section of the PR comment. Unfortunately, I do not have write access to this repository so I cannot add the "patch" label to this PR, but I did change the title.

**Comment by smithki** [comment]
> > Thank you for your contribution! 🙏
> > Just one thing, do you mind changing your PR label to a “patch” fix so it’s not misinterpreted the next time we cut a release?
> 
> No problem; I just fixed that in the 🗜 Versioning section of the PR comment. Unfortunately, I do not have write access to this repository so I cannot add the "patch" label to this PR, but I did change the title.

No worries, I'll take care of it for you :)

**Comment by smithki** [comment]
:rocket: PR was released in [`@magic-sdk/provider@3.0.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/provider%403.0.1), [`@magic-sdk/react-native@3.0.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/react-native%403.0.1), [`@magic-sdk/types@2.0.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/types%402.0.1), [`magic-sdk@3.0.1`](https://github.com/magiclabs/magic-js/releases/tag/magic-sdk%403.0.1) :rocket:

**Pull request merged**
