### PR TITLE
Remove webauthn feature

### PR DESCRIPTION
**Pull request by harryEth**
### 📦 Pull Request

Remove webauthn feature

### 🗜 Versioning

(Check _one!_)

- [ ] Patch: Bug Fix?
- [ ] Minor: New Feature?
- [x] Major: Breaking Change?

### ✅ Fixed Issues

- [List any fixed issues here like: Fixes #XXXX]

### 🚨 Test instructions

[Describe any additional context required to test the PR/feature/bug fix.]

### ⚠️ Update `CHANGELOG.md`

- [ ] I have updated the `Upcoming Changes` section of `CHANGELOG.md` with context related to this Pull Request.

### CODE REVIEW

**Comment by smithki** [comment]
Before you release this change (which is major version bump), we also have to remove `encodeQueryParameters` and `decodeQueryParameters` from `packages/provider/src/utils/base64-json.ts`. These are listed for deprecation at this version number.

**Review by smithki — APPROVED** [review]

**Comment by harryEth** [comment]
[ch25229]

**Comment by TheBolliwood** [comment]
Just out of interest: why was this feature deleted?

**Comment by smithki** [comment]
:rocket: PR was released in [`@magic-sdk/provider@3.0.0-next.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/provider%403.0.0-next.0), [`@magic-sdk/react-native@3.0.0-next.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/react-native%403.0.0-next.0), [`@magic-sdk/types@2.0.0-next.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/types%402.0.0-next.0), [`magic-sdk@3.0.0-next.0`](https://github.com/magiclabs/magic-js/releases/tag/magic-sdk%403.0.0-next.0) :rocket:

**Comment by smithki** [comment]
:rocket: PR was released in [`@magic-sdk/provider@3.0.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/provider%403.0.1), [`@magic-sdk/react-native@3.0.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/react-native%403.0.1), [`@magic-sdk/types@2.0.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/types%402.0.1), [`magic-sdk@3.0.1`](https://github.com/magiclabs/magic-js/releases/tag/magic-sdk%403.0.1) :rocket:

**Pull request merged**
